# Generated by Django 6.0.1 on 2026-02-01 16:49

from django.db import migrations, models
from django.utils import timezone


def set_timestamp_defaults(apps, schema_editor):
    """
    Set default values for timestamp fields on existing records
    Only handle models that exist at this migration point
    """
    Property = apps.get_model('api', 'Property')
    Tenant = apps.get_model('api', 'Tenant')
    Payment = apps.get_model('api', 'Payment')
    MaintenanceRequest = apps.get_model('api', 'MaintenanceRequest')
    
    now = timezone.now()
    
    # Update existing records with current timestamp
    for model in [Property, Tenant, Payment, MaintenanceRequest]:
        for obj in model.objects.all():
            if hasattr(obj, 'created_at') and not obj.created_at:
                obj.created_at = now
            if hasattr(obj, 'updated_at') and not obj.updated_at:
                obj.updated_at = now
            if hasattr(obj, 'timestamp') and not obj.timestamp:
                obj.timestamp = now
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_property_owner_tenant_user'),
    ]

    operations = [
        # Run the data migration to set timestamps
        migrations.RunPython(set_timestamp_defaults, migrations.RunPython.noop),
    ]
