# Generated by Django to fix corrupted migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_timestamp_defaults'),
    ]

    operations = [
    ]
