# Generated by Django - Empty migration to fix corrupted file

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_timestamp_defaults'),
    ]

    operations = [
    ]
