# Generated by Django 6.0.1 on 2026-02-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aimodelprediction_maintenancerequest_completed_at_and_more'),
        ('api', '0005_fix_corrupted_migration'),
    ]

    operations = [
    ]
