# Generated by Django 6.0.1 on 2026-02-01 17:11

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20260201_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('tenant_allocation', 'Tenant Allocation'), ('payment_prediction', 'Payment Prediction'), ('price_optimization', 'Price Optimization'), ('risk_assessment', 'Risk Assessment'), ('occupancy_forecast', 'Occupancy Forecast')], max_length=30)),
                ('input_data', models.JSONField()),
                ('prediction_result', models.JSONField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accurate', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='completion_time_predicted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='priority_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payment',
            name='days_overdue_predicted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(default=api.models.default_due_date),
        ),
        migrations.AddField(
            model_name='payment',
            name='late_payment_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='demand_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='occupancy_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('bedsitter', 'Bedsitter'), ('hostel', 'Student Hostel'), ('studio', 'Studio')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='behavior_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='late_payment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_reliability_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='preferred_property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('bedsitter', 'Bedsitter'), ('hostel', 'Student Hostel'), ('studio', 'Studio')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_satisfaction_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='total_payments_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('late', 'Late'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TenantBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(max_length=50)),
                ('behavior_data', models.JSONField()),
                ('risk_score', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(max_length=50)),
                ('preference_value', models.TextField()),
                ('importance_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='api.tenant')),
            ],
        ),
    ]
